# Use the official .NET SDK image as a base image
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build

# Set the working directory to 
C:\Users\vishws\C#Training\LoginAPI\LoginAPI

# Copy the .csproj file and restore dependencies
COPY *.csproj ./
RUN dotnet restore

# Copy the remaining files and build the application
COPY . .
RUN dotnet publish -c Release -o out

# Use a smaller runtime image
FROM mcr.microsoft.com/dotnet/aspnet:5.0

# Set the working directory to C:\Users\vishws\C#Training\LoginAPI\LoginAPI

# Copy the published app from the build image
COPY --from=build /app/out .

# Expose the port the app will run on
EXPOSE 53678

# Start the application
ENTRYPOINT ["dotnet", "LoginAPI.dll"]
