//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dell_trainingEntities3 : DbContext
    {
        public dell_trainingEntities3()
            : base("name=dell_trainingEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Employeemaster> Employeemasters { get; set; }
        public virtual DbSet<Like> Likes { get; set; }
        public virtual DbSet<Retweet> Retweets { get; set; }
        public virtual DbSet<Tweet> Tweets { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
    }
}
